#
# This is a project Makefile for the test subproject.
#
PROJECT_NAME := esp_t9062_test

EXTRA_COMPONENT_DIRS := $(realpath ../components)

TEST_COMPONENTS ?= esp_t9062

include $(IDF_PATH)/make/project.mk