#
# This is a project Makefile for the test subproject.
#
PROJECT_NAME := t9062_example_test

EXTRA_COMPONENT_DIRS := $(realpath ../components)

TEST_COMPONENTS ?= t9062

include $(IDF_PATH)/make/project.mk